### ISSUE TITLE
Token encryption requires a random string in keyphrase setting

### ISSUE THREAD

**Issue by biroby** [ltb-project/self-service-password#243]
Hi to all,
after setup and configure file config.local.inc.php i have the error in subject and i can't proceede to use tools.
Can anyone help me?

Thanks

**Comment by coudot** [comment]
Set a random value in $keyphrase:
```php
# Encryption, decryption keyphrase, required if $crypt_tokens = true
# Please change it to anything long, random and complicated, you do not have to remember it
# Changing it will also invalidate all previous tokens and SMS codes
$keyphrase = "abcdefgh";

**Comment by plewin** [comment]
Thank you, I am closing this issue because it was solved already.

**Comment by mbobak** [comment]
Hi,

I read through this, and I'm still getting the error, even after changing $keyphrase to:
$keyphrase = "TSDbyjhs!d4e1248dsdf$";

(yes, I'll change it again.)

Does anyone know why, after changing this, and then bouncing Apache, I still get the error?

Thanks,

-Mark

**Comment by mbobak** [comment]
I figured this out.  I was missing the first line of /usr/share/self-service-password/conf/config.inc.local.php, '<?php'.  When I added that in, everything started working.
